### ISSUE TITLE
Better error message on Json.read failure

### ISSUE THREAD

**Issue by haf** [xyncro/chiron#10] opened 2015-03-24 08:46 UTC
``` fsharp
        let inline read key =
                fromJson >> Json.ofResult
            =<< Json.getLensPartial (objectKeyPLens key) 

// snip

        let getLensPartial l : Json<_> =
            fun json ->
                match Lens.getPartial l json with
                | Some x -> Value x, json
                | _ -> Error "", json
```

returns an empty error message; it could possibly re-use they key to provide a nice error message "The property 'someKey' did not exist in the JSON structure".

**Comment by kolektiv** [comment] 2015-03-24 08:54
It should definitely return something non-empty! Giving a key might be tricky, as lenses are effectively opaque, so we don't know what element of the object was intended, but I'll come up with something...

**Comment by haf** [comment] 2015-03-27 10:02
Perhaps if you throw a typed exception instead of using 'failwith'? Or perhaps expose the error better?

**Comment by kolektiv** [comment] 2015-03-27 17:29
Yeah that's a good suggestion, it's hard to give much more useful detail, due to the opacity, but at least a non-generic exception would help. (Saying that, if the error could even be thrown here, tryGetLensPartial is probably a better choice!) But I'll change this, as it's not good enough :)

**Comment by haf** [comment] 2015-07-04 12:23
Ping?

**Comment by kolektiv** [comment] 2015-07-04 21:21
I'll pick this up and see what we can get in for 5.0 :)

**Comment by kolektiv** [comment] 2015-12-11 22:52
There's some excellent new stuff on this in 6.0.0-rc4 onwards (courtesy of @neoeinstein - i'm not taking any credit for that), so I'll close this off.

**Closed by kolektiv** 2015-12-11 22:52 UTC
